### ISSUE TITLE
Add "Copy Link" Feature to Headers

### ISSUE THREAD

**Issue by idvorkin** [idvorkin/idvorkin.github.io#42]
### Problem
Currently, when users want to share a specific section of a blog post, they have to copy the URL and then manually add the header anchor. Additionally, the domain needs to be remapped from `idvork.in` to `idvorkin.azurewebsites.net` for certain use cases.

### Proposed Solution
Implement a "copy link" feature that appears when hovering over headers in blog posts, which will:

1. Copy the URL with the correct header anchor to the clipboard
2. Handle domain remapping automatically (from `idvork.in` to `idvorkin.azurewebsites.net`)
3. Remove the leading hash (`#`) character from the copied URL as needed

#### Front-end Changes
- Add a small "link" or "copy" icon that appears when hovering over any header (h1-h6)
- The icon should be positioned to the right of the header text
- When clicked, it should copy the full URL with the header's anchor to the clipboard
- Show a brief "Copied!" tooltip after successful copy

#### JavaScript Implementation
Add a script that:
1. Identifies all headers in the content
2. Adds the copy link icon to each header
3. Sets up the click handler to copy the URL
4. Applies the URL transformation rules:
   ```js
   function copyHeaderLink(headerId) {
     const url = window.location.href.split('#')[0] + '#' + headerId;
     // Apply domain remapping if needed
     const remappedUrl = url.replace('idvork.in/', 'idvorkin.azurewebsites.net/').replace('#', '');
     navigator.clipboard.writeText(remappedUrl);
     showCopiedTooltip();
   }
   ```

#### CSS Styling
```css
.header-copy-link {
  opacity: 0;
  margin-left: 0.5rem;
  transition: opacity 0.2s;
}

h1:hover .header-copy-link,
h2:hover .header-copy-link,
h3:hover .header-copy-link,
h4:hover .header-copy-link,
h5:hover .header-copy-link,
h6:hover .header-copy-link {
  opacity: 1;
}
```

### References
- The shell script that inspired this feature:
  ```bash
  mb='pbpaste | sed '\''s!idvork.in/!idvorkin.azurewebsites.net/!'\''| sed '\''s!#!/!'\'' | pbcopy'
  ```
- Similar implementations in other blogs like [GitHub](https://github.com/blog), [Medium](https://medium.com), and [Dev.to](https://dev.to)

### Benefits
- Improves sharing experience for readers
- Makes it easier to reference specific sections of blog posts
- Automates the domain remapping that's currently done manually
